version: "3.8"
services:
  client:
    build:
      context: .
      target: client
    container_name: client
    ports:
      - '8000:80'
  admin:
    build:
      context: .
      target: admin
    container_name: admin
    ports:
      - '8001:80'
  backend:
    build: ./packages/api
    container_name: backend
    ports:
      - '3000:3000'